bmatsuo/lmdb-go

- lmdb/env.go
- lmdb/env_test.go
For convention, the method returns an error if the environment is not
open even though the C API returns only an invalid file descriptor.
> Implement Env.FD() method returning an open file description

- exp/lmdbscan/scanner.go
- exp/lmdbscan/scanner_test.go
Fixes #21
Method Scanner.Scan~~, Scanner.Set, and Scanner.SetNext~~ checks the
underlying cursor before calling Cursor.Get.  This allows a Scanner.Err
to catch an error opening the cursor even if called at the end of the
transaction.
If the Scanner method is called after the scanner has been closed then
a Scanner.Err is set to return an error indicating that the scanner is
closed.
edit: fix cherry-picked commit message
> lmdbscan: fix panic in Scanner.Scan after Txn.OpenCursor failed

- exp/lmdbscan/scanner_test.go
- exp/lmdbsync/handler_test.go
- exp/lmdbsync/lmdbsync_test.go
- internal/lmdbtest/lmdbtest.go
Fixes #24
Logic that was either repeated or is likely to be repeated was subsumed
into the new package.  The exp/lmdbscan and exp/lmdbsync packages have
had their tests converted to use the new package.
It's unclear if the core lmdb package can make use  of these helper
functions.  It is possible that, if a "black box" test style is used,
the internal package can be successfully imported.  But it is likely
that setup/teardown functions will need to remain defined in that
package.
> all: internal test package lmdbtest that performs common test tasks

- lmdb/env.go
The NewEnv function calls runtime.SetFinalizer the returned Env to
ensure that its Close method is called before garbage collection, when
its C-managed memory would otherwise leak.
> lmdb: adds a runtime finalizer to Env to reclaim memory

- lmdb/env.go
- lmdb/txn.go
- lmdb/txn_test.go
Fixes #27
Txn objects created by the Env.BeginTxn method now have a finalizer than
aborts them if they become unreachable before being committed.  Aside
from freeing memory this can help databases from growing indefinitely
and can also unlock an environment from a lost write transaction.  These
benefits are new for unmanaged transactions.  Managed transactions have
never had such shortcomings.
These benchmark comparisons should be taken with a grain of salt.  There
are some unexplained big swings.  But unmanaged transactions do not
appear to have a significant performance impact.  And renewed
transactions do not suffer from the finalizer.
benchmark                              old ns/op     new ns/op     delta
BenchmarkEnv_ReaderList-4              72344         73023         +0.94% …
> lmdb: adds finalizer to unmanaged Txn objects, aborting them before gc

- lmdb/cursor.go
- lmdb/env.go
- lmdb/txn.go
Fixes #28
The Cursor.Close function is made idempotent as there is no way to tell
when a cursor is closed.  The Cursor.Close method will not call
mdb_cursor_close if the cursor's write transaction has closed because
resources have bene reclaimed.
A finalizer is used for only for readonly cursors because write
transactions will close their cursors on termination.
benchmark                              old ns/op     new ns/op     delta
BenchmarkEnv_ReaderList-4              78711         71540         -9.11%
BenchmarkTxn_Put-4                     1732          1712          -1.15%
BenchmarkTxn_PutReserve-4              1702          1727          +1.47%
BenchmarkTxn_PutReserve_writemap-4     1465          1443          -1.50%
BenchmarkTxn_Put_writemap-4            1446          1435 …
> lmdb: add finalizer for readonly Cursors; fix obsure SIGABRT

- lmdb/cursor.go
- lmdb/cursor_test.go
Fixes #31
The returned DBI is the maximum value for the DBI type.  It shouldn't be
possible to actually have that many open databases because the address
space would be exhausted.  So any attempt to use the returned value will
result in an error.
> lmdb: Cursor.DBI returns an "invalid" DBI if the cursor has been closed

- lmdb/lmdb.go
Clang on OS X warns when making test:
```
lmdb/mdb.c:9466:46: warning: data argument not used by format string [-Wformat-extra-args]
```
The code in question uses a ternary statement to decide which format string to use, which Clang is not
smart enough to figure out.
You can argue this should be two sprintf() calls, but I'd rather not modify the LMDB source.
> Fix spurious compiler warning on OS X

- lmdb/env.go
- lmdb/env_test.go
- lmdb/lmdbgo.c
- lmdb/msgfunc.go
- lmdb/msgfunc_test.go
When Env.ReaderList is called with a nil function argument it
behaves as if mdb_env_reader_list() was called with a NULL function
argument, returning an error.  Calling ReaderList on an invalid Env
returns an error as well, but has done so for a long time.
> lmdb: fix return value of Env.ReaderList when passed invalid arguments

- lmdb/cursor.go
- lmdb/txn.go
- lmdb/val.go
- lmdb/val_test.go
The mdbVal type was vestigial after updating for the cgo changes in go1.6. I extracted the meaningful functions and removed the type definition.
> lmdb: clean up C.MDB_val internals

- exp/lmdbsync/handler.go
- exp/lmdbsync/handler_test.go
- exp/lmdbsync/testresize_test.go
Fixes #54 
A DelayFunc type is defined to describe the interface for
MapResizedHandler.  The delay function is called before each call to
Env.SetMapSize including the first, when its argument is zero.  This is
an incompatible change for lmdbsync.
Additionally, the default values for MapResizedHandler arguments have
been renamed so that they more clearly reflect their purpose.  Their
previous names made no sense to users as they corresponded to field
names for unexported structs.
> lmdbsync: changes to MapResizedHandler delays and defaults

- .travis.yml
The dependency on the go/types package breaks compilation on earlier
versions.
> recently golint was made to only compile for go version >=1.5

- README.md
- lmdb/lmdb.go
This is a small optimization, which turns a seek + writev into a pwritev syscall on Linux.
> lmdb: Enable MDB_USE_PWRITEV on Linux

- lmdb/cursor.go
- lmdb/cursor_test.go
- lmdb/txn.go
- lmdb/txn_test.go
- lmdb/val.go
- lmdb/val_test.go
Fixes #56 
The `valBytes()` function has been modified to return a non-empty slice of bytes for any (possibly empty) input slice. The length returned is always the true length of the input.
This is a hack that allows the cgo tool to correctly identify the argument type as the slice and not the bytes.Buffer (or whatever containing type causes these types of panics).
> Fix cgo argument check panic for small slices from bytes.Buffer (and similar types)

- lmdb/cursor.go
- lmdb/txn.go
> lmdb: internal C.MDB_val fields in Txn for re-use during Get/PutReserve

- lmdb/cursor.go
- lmdb/lmdbgo.c
- lmdb/lmdbgo.h
- lmdb/txn.go
> Switch void* C arguments to char* to avoid allocations and linear data check

- lmdb/val.go
Fixes #67 
Uses a temporary conversion from unsafe.Pointer to `*[valMaxSize]byte` to create a slice of the actual data length (and capacity).
edit: It  does not appear to slow anything down. If anything it makes things slightly faster. And it avoids a direct dependency on the "reflect" package.
> lmdb: slice pointers without reflect

- lmdb/env.go
- lmdb/error.go
- lmdb/error_test.go
It was only being used in a couple places (outside of tests).  So
existing trivial usages of Errorf were replaced with errors.New and the
OpError.Error method was rewritten to use string concatenation, which
ends up being faster and using fewer allocations.  Though in practice
the performance of error message serialization is not going to impact an
application in a stable production environment.
> lmdb: remove direct dependency on the fmt package

- cmd/lmdb_stat/main.go
`lmdb_stat` currently does not correctly decode the txnid of freelist entries. I've also made small changes so that the output is 1:1 with `mdb_stat`.
> Fix wrong decoding of txnid and differing output in lmdb_stat

- internal/lmdbarch/width.go
- lmdb/val.go
Fixes #81
The package detects architecture bit-width using techniques from the
runtime package to avoid duplication and omission of code for various
architectures.
The architecture detection hacks are moved to their own internal package
to avoid golint complaining about weird looking constant formulae.
> lmdb: use 31-bit lengths when on 32-bit architectures

- CHANGES.md
- README.md
It wouldn't be prudent to bundle the changes from #99/#11 into a release that also contains an upgrade of LMDB and the stabilization of the lmdbscan package. So the release should be cut now to allow a relatively clean slate for #99 to land.
> Release v1.8.0

- lmdb/txn_test.go
I have seen occasional deadlocking while running benchmarks and #94 spurred me to look into the possibility that some benchmarks have been unsafely creating write transactions. I did find several such instances. It is hard to tell if the infrequent deadlocks I experienced are gone for good but this can't really hurt.
> lmdb: Benchmarks calling BeginTxn without Readonly lock their threads

- lmdb/env.go
- lmdb/txn.go
Update transactions must execute exclusively and it is OK for these
transactions to share two C.MDB_val object that are alive for entire
existence of the Env object.
View transactions cannot use these C.MDB_val objects because they may
execute concurrently with other View transactions or an Update
transaction.
> lmdb: Update transactions share C-allocated C.MDB_val objects

- README.md
- exp/lmdbpool/doc.go
- exp/lmdbpool/put.go
- exp/lmdbpool/putrace.go
- exp/lmdbpool/txnpool.go
- lmdb/env.go
- lmdb/txn.go
Fixes #104 
In addition to removing the undocumented finalizer behavior in Txn.Reset and Txn.Renew which, as #104 points out, was never a good idea or a safe one. I have gone on to try and ensure that lmdb.Txn and sync.Pool can be used together effectively (to whatever extent that is truly possible).
There are some questions about how sync.Pool and lmdb.Txn truly interact, mostly because of how poorly defined finalizers are. In testing it has been seen that naive pooling fails terribly if the application has been compiled with `-race`. The interaction with `-race` was so bad that it spurred the creation of a new experimental package lmdbpool, which contains a workaround for race detection using build tags.
At this point I'm not completely certain if there are unforeseen problems in …
> Keep finalizer on Txn.Reset and address incompatibilities of Txn and sync.Pool

- lmdb/lmdb.go
Compiling this package on clang currently generates the following bogus warnings:
$ go test ./lmdb
lmdb/mdb.c:9100:20: warning: missing field 'mc_backup' initializer [-Wmissing-field-initializers]
lmdb/mdb.c:9258:18: warning: missing field 'mc_txn' initializer [-Wmissing-field-initializers]
ok      github.com/bmatsuo/lmdb-go/lmdb    0.380s
Add a flag to the CGO implementation which suppresses this output. See https://bugs.llvm.org//show_bug.cgi?id=21689 for the upstream bug.
> lmdb: Silence missing initializers error on clang

- lmdb/bench_test.go
It is not obvious that an update transaction will be faster than a
Readonly transaction, even when renewing both the Txn and Cursor object.
This benchmark rework is the first in a series that I hope to make, and
that I hope will continue to bring meaningful insight into LMDB
performance, unlike many of the existing benchmarks.
> Rework BenchmarkScan to benchmark Txn.Renew

- lmdb/bench_test.go
This shows that using Readonly transactions with Reset/Renew has
benefits for small transactions, where resource allocation appears to
dominate runtime.  However, as the number of operations in transactions
increase overhead in Readonly becomes more apparent.
> lmdb: Add benchmarks that batch various numbers of ops in single txns

- lmdb/env.go
- lmdb/txn.go
This is fairly convenient because it is a reasonably fast path for the
most common managed transactions.
Also, this addition will properly panic when `commit` is supplied from a managed transaction, which was a bug in the previous implementation.
> lmdb: Txn.RunOp splits into two implementations based on termination

- exp/lmdbpool/txnpool.go
- lmdb/txn.go
- lmdb/txn_test.go
Checking of Txn.ID() for lmdb.Readonly transactions now occurs at the correct location (as a Txn would enter the pool as opposed to when it exits the pool).
There is also an optimization that allows Txn.ID() to cache the value it gets for future calls. This requires some bookkeeping because there are times when a transaction's ID may change. But the logic behind this in LMDB is straight forward and there are some tests to make sure that Txn.ID() does transparently represent the value returned by `mdb_txn_id`.
> lmdbpool: Improvements to TxnPool

- exp/lmdbpool/txnpool.go
A new goroutine is spawned for each update.  This may turn out to be too
costly.  We want updates to complete as fast as possible and handling
the idle transactions in that goroutine is not practical.  So it really
just comes down to doing things this way or using a permanent working
goroutine that would require more management/bookkeeping.
> lmdbpool: TxnPool.CommitID handles idle transactions in the pool

- README.md
Fixes #112 
gocover.io has not implemented a reasonable badge system for years now.
So I'm done waiting for it.  I don't think coveralls is free, otherwise
that seems OK.  I'm not sure of free alternatives.
> Remove coverage badges from the README because they aren't accurate
